# Generated by Django 4.0.1 on 2022-04-05 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='screens',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('screen_name', models.CharField(default='null', max_length=255)),
                ('building_name', models.CharField(default='null', max_length=255)),
                ('location', models.CharField(default='null', max_length=100)),
                ('address', models.CharField(default='null', max_length=500)),
                ('city', models.CharField(default='null', max_length=100)),
                ('state', models.CharField(default='null', max_length=20000)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='FILM_PEOPLE/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
