# Generated by Django 4.0.1 on 2022-03-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filim_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='state',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
