# Generated by Django 4.0.1 on 2022-03-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filim_user', '0002_alter_registration_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='FILM_USER/'),
        ),
    ]
