# Generated by Django 4.0.1 on 2022-04-03 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filim_pro', '0013_movie_cast_crew'),
        ('filim_user', '0003_alter_registration_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie_rating',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating_scale', models.FloatField(default=0, max_length=10)),
                ('rating_title', models.CharField(default='null', max_length=500)),
                ('rating', models.CharField(default='null', max_length=20000)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filim_pro.movie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filim_user.registration')),
            ],
        ),
    ]
