# Generated by Django 4.0.1 on 2022-04-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filim_user', '0004_movie_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_rating',
            old_name='rating',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='movie_rating',
            old_name='rating_title',
            new_name='review_title',
        ),
    ]
