# Generated by Django 4.0.1 on 2022-04-04 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filim_user', '0005_rename_rating_movie_rating_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_rating',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='movie_rating',
            old_name='user_id',
            new_name='user',
        ),
    ]
