# Generated by Django 4.0.1 on 2022-04-04 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filim_user', '0006_rename_movie_id_movie_rating_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_rating',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
