# Generated by Django 4.0.1 on 2022-04-04 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filim_user', '0007_movie_rating_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
