# Generated by Django 4.0.1 on 2022-03-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filim_pro', '0003_alter_registration_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='people',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(default='null', max_length=255)),
                ('lastname', models.CharField(default='null', max_length=255)),
                ('data_of_birth', models.CharField(default='null', max_length=100)),
                ('biography', models.CharField(default='null', max_length=20000)),
                ('cast_crew', models.CharField(default='null', max_length=100)),
                ('position', models.CharField(default='null', max_length=100)),
            ],
        ),
    ]
