# Generated by Django 4.0.1 on 2022-03-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filim_pro', '0004_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='FILM_PEOPLE/'),
        ),
    ]
