# Generated by Django 4.0.1 on 2022-03-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filim_pro', '0005_people_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='country',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
