# Generated by Django 4.0.1 on 2022-03-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filim_pro', '0006_people_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='data_of_birth',
            new_name='date_of_birth',
        ),
    ]
