# Generated by Django 4.0.1 on 2022-03-29 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filim_pro', '0007_rename_data_of_birth_people_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='people_photo',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='FILM_PRO/')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filim_pro.people')),
            ],
        ),
    ]
