# Generated by Django 4.0.1 on 2022-03-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filim_pro', '0008_people_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='null', max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='FILM_MOVIE/')),
                ('overview', models.CharField(default='null', max_length=20000)),
                ('release_date', models.CharField(default='null', max_length=100)),
                ('running_time', models.CharField(default='null', max_length=100)),
                ('certificate', models.CharField(default='null', max_length=100)),
                ('trailer_link', models.CharField(default='null', max_length=100, null=True)),
            ],
        ),
    ]
