# Generated by Django 4.0.1 on 2022-03-30 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filim_pro', '0010_movie_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie_photo',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='FILM_PRO/')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filim_pro.movie')),
            ],
        ),
    ]
