# Generated by Django 4.0.1 on 2022-03-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filim_pro', '0011_movie_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genere',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
