# Generated by Django 4.0.1 on 2022-03-30 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filim_pro', '0012_movie_genere'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie_cast_crew',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('cast', 'Cast'), ('crew', 'Crew')], default='cast', max_length=15)),
                ('title', models.CharField(default='null', max_length=100, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filim_pro.movie')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filim_pro.people')),
            ],
        ),
    ]
