# Generated by Django 4.0.1 on 2022-04-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filim_pro', '0014_movie_date_added_movie_cast_crew_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='position',
            field=models.CharField(default='null', max_length=500),
        ),
    ]
